import json
import os
import requests
from dotenv import load_dotenv
from flask import Flask, request, session, render_template, flash
from requests.auth import HTTPBasicAuth
import numpy as np
import joblib
import xgboost as xgb
import urllib.parse
import pandas as pd
from pathlib import Path


MODEL_PATH = Path(__file__).resolve().parent / "artifacts/telco_customer_churn/clf_xgb.json"
model = xgb.XGBClassifier()
model.load_model(MODEL_PATH)
PREPROCESSOR_PATH = Path(__file__).resolve().parent / "artifacts/telco_customer_churn/preprocessing.joblib"
preprocessor = joblib.load(PREPROCESSOR_PATH)

app = Flask(__name__)

app.config.update(dict(DEBUG=True, SECRET_KEY=os.environ.get("SECRET_KEY", "development key")))

strings = {
    "City": [
        "Los_Angeles",
        "Beverly_Hills",
        "Huntington_Park",
        "Lynwood",
        "Marina_Del_Rey",
        "Inglewood",
        "Santa_Monica",
        "Torrance",
        "Whittier",
        "La_Habra",
        "Pico_Rivera",
        "Avalon",
        "Harbor_City",
        "Lakewood",
        "Los_Alamitos",
        "San_Pedro",
        "Carson",
        "Long_Beach",
        "Altadena",
        "Monrovia",
        "Sierra_Madre",
        "Tujunga",
        "Pasadena",
        "Glendale",
        "Canoga_Park",
        "Mission_Hills",
        "Santa_Clarita",
        "Sun_Valley",
        "Stevenson_Ranch",
        "Panorama_City",
        "Van_Nuys",
        "Burbank",
        "North_Hollywood",
        "Covina",
        "El_Monte",
        "La_Puente",
        "Rowland_Heights",
        "Ontario",
        "Pomona",
        "Rosemead",
        "San_Dimas",
        "West_Covina",
        "Alhambra",
        "Alpine",
        "Bonita",
        "Boulevard",
        "Guatay",
        "Jacumba",
        "Mount_Laguna",
        "Borrego_Springs",
        "Carlsbad",
        "Del_Mar",
        "El_Cajon",
        "Escondido",
        "Oceanside",
        "Pala",
        "Palomar_Mountain",
        "Pauma_Valley",
        "Ranchita",
        "Valley_Center",
        "San_Diego",
        "Indio",
        "Indian_Wells",
        "Palm_Desert",
        "Desert_Hot_Springs",
        "Holtville",
        "Niland",
        "North_Palm_Springs",
        "Ocotillo",
        "Seeley",
        "Thermal",
        "Adelanto",
        "Apple_Valley",
        "Crestline",
        "Daggett",
        "Ludlow",
        "Lucerne_Valley",
        "Lytle_Creek",
        "Phelan",
        "Redlands",
        "Rialto",
        "Running_Springs",
        "Tecopa",
        "Victorville",
        "Wrightwood",
        "San_Bernardino",
        "Riverside",
        "March_Air_Reserve_Base",
        "Hemet",
        "Homeland",
        "Idyllwild",
        "Moreno_Valley",
        "Murrieta",
        "Perris",
        "Sun_City",
        "Irvine",
        "Lake_Forest",
        "Huntington_Beach",
        "Newport_Beach",
        "Santa_Ana",
        "Anaheim",
        "Brea",
        "Norco",
        "Yorba_Linda",
        "Ventura",
        "Port_Hueneme",
        "Summerland",
        "Santa_Barbara",
        "Alpaugh",
        "Armona",
        "Avenal",
        "Bodfish",
        "Camp_Nelson",
        "Coalinga",
        "Delano",
        "Earlimart",
        "Exeter",
        "Fellows",
        "Huron",
        "Kernville",
        "Lemon_Cove",
        "Lindsay",
        "Maricopa",
        "Onyx",
        "Posey",
        "Shafter",
        "Tipton",
        "Wofford_Heights",
        "Visalia",
        "Bakersfield",
        "San_Luis_Obispo",
        "Lompoc",
        "Los_Alamos",
        "Oceano",
        "Pismo_Beach",
        "Mojave",
        "Johannesburg",
        "Keene",
        "Lancaster",
        "Palmdale",
        "Pearblossom",
        "Randsburg",
        "Ridgecrest",
        "Trona",
        "Bass_Lake",
        "Biola",
        "Five_Points",
        "Friant",
        "Kerman",
        "Madera",
        "Mendota",
        "Miramonte",
        "Orosi",
        "Fresno",
        "San_Joaquin",
        "Selma",
        "South_Dos_Palos",
        "Tollhouse",
        "Squaw_Valley",
        "Big_Sur",
        "Carmel",
        "Jolon",
        "King_City",
        "Lockwood",
        "Marina",
        "Pebble_Beach",
        "Belmont",
        "Daly_City",
        "Loma_Mar",
        "Los_Altos",
        "Mountain_View",
        "Pescadero",
        "San_Bruno",
        "South_San_Francisco",
        "Sunnyvale",
        "San_Francisco",
        "Palo_Alto",
        "San_Mateo",
        "Antioch",
        "Birds_Landing",
        "Byron",
        "Concord",
        "Fremont",
        "Hayward",
        "Castro_Valley",
        "Livermore",
        "Martinez",
        "Napa",
        "Pinole",
        "Pleasanton",
        "San_Leandro",
        "San_Lorenzo",
        "San_Ramon",
        "Union_City",
        "Walnut_Creek",
        "Oakland",
        "Berkeley",
        "Albany",
        "San_Rafael",
        "Greenbrae",
        "Bodega_Bay",
        "Cotati",
        "Forest_Knolls",
        "Larkspur",
        "Marshall",
        "Novato",
        "Nicasio",
        "San_Anselmo",
        "Sausalito",
        "Tomales",
        "Valley_Ford",
        "Alviso",
        "Boulder_Creek",
        "Davenport",
        "Freedom",
        "Gilroy",
        "Los_Gatos",
        "San_Martin",
        "Santa_Cruz",
        "San_Jose",
        "Stockton",
        "Acampo",
        "Glencoe",
        "Linden",
        "Lodi",
        "Valley_Springs",
        "West_Point",
        "Atwater",
        "Big_Oak_Flat",
        "Columbia",
        "Delhi",
        "Hickman",
        "Long_Barn",
        "Mariposa",
        "Mi_Wuk_Village",
        "Modesto",
        "Oakdale",
        "Riverbank",
        "Salida",
        "Snelling",
        "Turlock",
        "Westley",
        "Yosemite_National_Park",
        "Santa_Rosa",
        "Branscomb",
        "Caspar",
        "Clearlake",
        "Cloverdale",
        "Comptche",
        "Eldridge",
        "Fulton",
        "Gualala",
        "Nice",
        "Rio_Nido",
        "Ukiah",
        "Witter_Springs",
        "Alderpoint",
        "Mckinleyville",
        "Bayside",
        "Blue_Lake",
        "Bridgeville",
        "Crescent_City",
        "Ferndale",
        "Honeydew",
        "Korbel",
        "Loleta",
        "Miranda",
        "Rio_Dell",
        "Salyer",
        "Smith_River",
        "Somes_Bar",
        "Trinidad",
        "Whitethorn",
        "Amador_City",
        "Carmichael",
        "Davis",
        "Diamond_Springs",
        "Dixon",
        "Elk_Grove",
        "Elmira",
        "Folsom",
        "Greenwood",
        "Jackson",
        "Knights_Landing",
        "Madison",
        "Orangevale",
        "Penryn",
        "Pleasant_Grove",
        "Plymouth",
        "Rio_Linda",
        "Sheridan",
        "Sloughhouse",
        "Wheatland",
        "Winters",
        "Colfax",
        "Meadow_Vista",
        "Soda_Springs",
        "Rancho_Cordova",
        "Sacramento",
        "Antelope",
        "Arbuckle",
        "Bangor",
        "Canyon_Dam",
        "Challenge",
        "Dobbins",
        "Dunnigan",
        "Forest_Ranch",
        "Grass_Valley",
        "Magalia",
        "Nevada_City",
        "Oroville",
        "Princeton",
        "Strawberry_Valley",
        "Twain",
        "Yuba_City",
        "Anderson",
        "Big_Bend",
        "Callahan",
        "Corning",
        "Cottonwood",
        "Douglas_City",
        "Fall_River_Mills",
        "Fort_Jones",
        "Hayfork",
        "Igo",
        "Klamath_River",
        "Lakehead",
        "Lewiston",
        "Nubieber",
        "Palo_Cedro",
        "Round_Mountain",
        "Seiad_Valley",
        "Shasta",
        "Vina",
        "Alturas",
        "Davis_Creek",
        "Fort_Bidwell",
        "Lake_City",
        "Likely",
        "Portola",
        "Ravendale",
        "Topaz",
        "Homewood",
        "Tahoma",
        "Tahoe_City",
        "South_Lake_Tahoe",
        "Truckee",
        "Culver_City",
        "Hawthorne",
        "Hermosa_Beach",
        "Malibu",
        "Pacific_Palisades",
        "Redondo_Beach",
        "Buena_Park",
        "La_Palma",
        "Stanton",
        "Bellflower",
        "Lomita",
        "Seal_Beach",
        "South_Pasadena",
        "Sunland",
        "Agoura_Hills",
        "Newhall",
        "Northridge",
        "Porter_Ranch",
        "Pacoima",
        "Reseda",
        "Sylmar",
        "Granada_Hills",
        "Canyon_Country",
        "Westlake_Village",
        "Sherman_Oaks",
        "Chino",
        "Claremont",
        "Monterey_Park",
        "Walnut",
        "Chula_Vista",
        "Dulzura",
        "Jamul",
        "Bonsall",
        "Cardiff_By_The_Sea",
        "Encinitas",
        "La_Jolla",
        "Ramona",
        "San_Marcos",
        "Santee",
        "Vista",
        "Coronado",
        "Banning",
        "Desert_Center",
        "Heber",
        "La_Quinta",
        "Rancho_Mirage",
        "Twentynine_Palms",
        "Westmorland",
        "Amboy",
        "Angelus_Oaks",
        "Baker",
        "Cedar_Glen",
        "Colton",
        "Fawnskin",
        "Fontana",
        "Mentone",
        "Sugarloaf",
        "Anza",
        "Nuevo",
        "Foothill_Ranch",
        "Corona_Del_Mar",
        "Dana_Point",
        "Midway_City",
        "Newport_Coast",
        "Trabuco_Canyon",
        "Garden_Grove",
        "Camarillo",
        "Moorpark",
        "Oak_View",
        "Oxnard",
        "Piru",
        "Santa_Paula",
        "Buttonwillow",
        "Mc_Kittrick",
        "Taft",
        "Terra_Bella",
        "Los_Osos",
        "Bradley",
        "Buellton",
        "Morro_Bay",
        "Nipomo",
        "Templeton",
        "Benton",
        "Independence",
        "Inyokern",
        "Lee_Vining",
        "Rosamond",
        "Tehachapi",
        "Cantua_Creek",
        "Clovis",
        "Cutler",
        "Dinuba",
        "Dunlap",
        "Fowler",
        "Hume",
        "North_Fork",
        "Oakhurst",
        "Prather",
        "Tranquillity",
        "Traver",
        "Salinas",
        "Carmel_Valley",
        "San_Lucas",
        "Brisbane",
        "Burlingame",
        "Atherton",
        "Pleasant_Hill",
        "Crockett",
        "Danville",
        "Fairfield",
        "Travis_Afb",
        "Moraga",
        "Orinda",
        "Pope_Valley",
        "Dublin",
        "Rodeo",
        "Saint_Helena",
        "Deer_Park",
        "Sunol",
        "Vallejo",
        "Emeryville",
        "El_Sobrante",
        "Richmond",
        "Inverness",
        "Mill_Valley",
        "Stinson_Beach",
        "Aromas",
        "Moss_Landing",
        "San_Juan_Bautista",
        "Santa_Clara",
        "Angels_Camp",
        "Avery",
        "Hathaway_Pines",
        "Mountain_Ranch",
        "Sheep_Ranch",
        "Vallecito",
        "Ballico",
        "Catheys_Valley",
        "Merced",
        "Newman",
        "Patterson",
        "Planada",
        "Soulsbyville",
        "Waterford",
        "Clearlake_Oaks",
        "Covelo",
        "Guerneville",
        "Healdsburg",
        "Jenner",
        "Philo",
        "Point_Arena",
        "Westport",
        "The_Sea_Ranch",
        "Eureka",
        "Gasquet",
        "Hydesville",
        "Klamath",
        "Piercy",
        "West_Sacramento",
        "Brooks",
        "Citrus_Heights",
        "El_Dorado",
        "Elverta",
        "Garden_Valley",
        "Grizzly_Flats",
        "Guinda",
        "Herald",
        "Isleton",
        "Lotus",
        "Mather",
        "Newcastle",
        "Nicolaus",
        "Pilot_Hill",
        "Pine_Grove",
        "Rio_Oso",
        "Roseville",
        "Thornton",
        "Woodland",
        "Applegate",
        "Camino",
        "Dutch_Flat",
        "Echo_Lake",
        "Pollock_Pines",
        "Weimar",
        "Granite_Bay",
        "Beale_Afb",
        "Butte_City",
        "Camptonville",
        "Chico",
        "Clipper_Mills",
        "Colusa",
        "Downieville",
        "Grimes",
        "Palermo",
        "Quincy",
        "Rough_And_Ready",
        "Sutter",
        "Willows",
        "Adin",
        "Bieber",
        "Burney",
        "Dorris",
        "Mineral",
        "Montague",
        "Oak_Run",
        "Old_Station",
        "Paskenta",
        "Red_Bluff",
        "Weaverville",
        "Whitmore",
        "Blairsden_Graeagle",
        "Doyle",
        "Eagleville",
        "Sierra_City",
        "Sierraville",
        "Westwood",
        "Tahoe_Vista",
        "Compton",
        "Gardena",
        "Lawndale",
        "Montebello",
        "Santa_Fe_Springs",
        "Sunset_Beach",
        "Arcadia",
        "Chatsworth",
        "Encino",
        "Valencia",
        "Tarzana",
        "Castaic",
        "Valley_Village",
        "Glendora",
        "Mira_Loma",
        "Campo",
        "La_Mesa",
        "Spring_Valley",
        "Fallbrook",
        "San_Ysidro",
        "Brawley",
        "Calexico",
        "Palm_Springs",
        "Thousand_Palms",
        "White_Water",
        "Big_Bear_City",
        "Bloomington",
        "Calimesa",
        "Green_Valley_Lake",
        "Hinkley",
        "Newberry_Springs",
        "Oro_Grande",
        "Lake_Elsinore",
        "Temecula",
        "Costa_Mesa",
        "Silverado",
        "Rancho_Santa_Margarita",
        "Ladera_Ranch",
        "Tustin",
        "Fullerton",
        "Orange",
        "Placentia",
        "Corona",
        "Carpinteria",
        "Ojai",
        "Somis",
        "Ducor",
        "Frazier_Park",
        "Lemoore",
        "Porterville",
        "Sequoia_National_Park",
        "Strathmore",
        "Wasco",
        "Woody",
        "Casmalia",
        "Guadalupe",
        "Boron",
        "Edwards",
        "Lake_Hughes",
        "Valyermo",
        "Ahwahnee",
        "Big_Creek",
        "Helm",
        "Kingsburg",
        "Parlier",
        "Sanger",
        "Shaver_Lake",
        "Pacific_Grove",
        "Seaside",
        "Half_Moon_Bay",
        "Millbrae",
        "Redwood_City",
        "Calistoga",
        "Lafayette",
        "Pittsburg",
        "Port_Costa",
        "Rio_Vista",
        "San_Pablo",
        "Bolinas",
        "Corte_Madera",
        "Point_Reyes_Station",
        "Capitola",
        "Cupertino",
        "Milpitas",
        "Morgan_Hill",
        "Arnold",
        "Campo_Seco",
        "Clements",
        "French_Camp",
        "Lockeford",
        "Murphys",
        "Wallace",
        "Crows_Landing",
        "Gustine",
        "Hughson",
        "La_Grange",
        "Lathrop",
        "Pinecrest",
        "Stevinson",
        "Vernalis",
        "Winton",
        "Cobb",
        "Elk",
        "Glen_Ellen",
        "Mendocino",
        "Redwood_Valley",
        "Sonoma",
        "Fields_Landing",
        "Hoopa",
        "Myers_Flat",
        "Samoa",
        "Zenia",
        "Auburn",
        "Clarksburg",
        "Fair_Oaks",
        "Galt",
        "Hood",
        "Loomis",
        "Pioneer",
        "Vacaville",
        "Walnut_Grove",
        "Emigrant_Gap",
        "Browns_Valley",
        "Crescent_Mills",
        "Elk_Creek",
        "Hamilton_City",
        "Live_Oak",
        "Maxwell",
        "Meadow_Valley",
        "Olivehurst",
        "Williams",
        "Bella_Vista",
        "Castella",
        "Happy_Camp",
        "Hat_Creek",
        "Paynes_Creek",
        "Shingletown",
        "Trinity_Center",
        "Susanville",
        "Termo",
        "Carnelian_Bay",
        "Kings_Beach",
        "Downey",
        "El_Segundo",
        "Topanga",
        "Venice",
        "Cerritos",
        "Duarte",
        "Montrose",
        "San_Marino",
        "Woodland_Hills",
        "Azusa",
        "Rancho_Cucamonga",
        "Hacienda_Heights",
        "San_Gabriel",
        "Imperial_Beach",
        "Julian",
        "Lakeside",
        "Solana_Beach",
        "Rancho_Santa_Fe",
        "Blythe",
        "Coachella",
        "Imperial",
        "Joshua_Tree",
        "Parker_Dam",
        "Vidal",
        "Winterhaven",
        "Landers",
        "Barstow",
        "Highland",
        "Shoshone",
        "Yermo",
        "Yucaipa",
        "Aguanga",
        "San_Jacinto",
        "Capistrano_Beach",
        "Laguna_Beach",
        "Mission_Viejo",
        "Simi_Valley",
        "California_Hot_Springs",
        "Corcoran",
        "Farmersville",
        "Ivanhoe",
        "Lebec",
        "New_Cuyama",
        "Richgrove",
        "Stratford",
        "Tulare",
        "Solvang",
        "Big_Pine",
        "Caliente",
        "Lone_Pine",
        "Olancha",
        "Badger",
        "Riverdale",
        "Carmel_By_The_Sea",
        "Chualar",
        "Greenfield",
        "Portola_Valley",
        "Angwin",
        "Clayton",
        "Oakley",
        "Rohnert_Park",
        "Olema",
        "Woodacre",
        "Aptos",
        "Ben_Lomond",
        "Campbell",
        "Felton",
        "Hollister",
        "Watsonville",
        "Woodbridge",
        "Denair",
        "Groveland",
        "Jamestown",
        "Livingston",
        "Tuolumne",
        "Annapolis",
        "Graton",
        "Hopland",
        "Lakeport",
        "Laytonville",
        "Lucerne",
        "Navarro",
        "Yorkville",
        "Burnt_Ranch",
        "Garberville",
        "Petrolia",
        "Redway",
        "Cool",
        "Kirkwood",
        "Rescue",
        "Sutter_Creek",
        "Wilton",
        "Kyburz",
        "Brownsville",
        "Forbestown",
        "Gridley",
        "Orland",
        "Taylorsville",
        "Redding",
        "Canby",
        "Cassel",
        "Shasta_Lake",
        "Dunsmuir",
        "Etna",
        "Flournoy",
        "Greenview",
        "Hornbrook",
        "Los_Molinos",
        "Mcarthur",
        "Mill_Creek",
        "Platina",
        "Wendel",
        "West_Hollywood",
        "Hawaiian_Gardens",
        "Paramount",
        "La_Canada_Flintridge",
        "Winnetka",
        "San_Fernando",
        "North_Hills",
        "Thousand_Oaks",
        "South_El_Monte",
        "Montclair",
        "Poway",
        "Beaumont",
        "Cabazon",
        "Calipatria",
        "El_Centro",
        "Bell",
        "Manhattan_Beach",
        "Maywood",
        "Palos_Verdes_Peninsula",
        "Rancho_Palos_Verdes",
        "South_Gate",
        "Playa_Del_Rey",
        "Cypress",
        "La_Mirada",
        "Norwalk",
        "Artesia",
        "Surfside",
        "Wilmington",
        "La_Crescenta",
        "Calabasas",
        "West_Hills",
        "Newbury_Park",
        "Oak_Park",
        "Studio_City",
        "Baldwin_Park",
        "Chino_Hills",
        "La_Verne",
        "Mt_Baldy",
        "Diamond_Bar",
        "Temple_City",
        "Upland",
        "Descanso",
        "Lemon_Grove",
        "National_City",
        "Pine_Valley",
        "Potrero",
        "Tecate",
        "Santa_Ysabel",
        "Warner_Springs",
        "Cathedral_City",
        "Earp",
        "Mecca",
        "Morongo_Valley",
        "Palo_Verde",
        "Pioneertown",
        "Salton_City",
        "Yucca_Valley",
        "Fort_Irwin",
        "Grand_Terrace",
        "Big_Bear_Lake",
        "Death_Valley",
        "Essex",
        "Forest_Falls",
        "Helendale",
        "Hesperia",
        "Lake_Arrowhead",
        "Loma_Linda",
        "Needles",
        "Nipton",
        "Pinon_Hills",
        "Mountain_Center",
        "Menifee",
        "Wildomar",
        "Winchester",
        "Laguna_Hills",
        "Aliso_Viejo",
        "San_Clemente",
        "San_Juan_Capistrano",
        "Laguna_Niguel",
        "Westminster",
        "Fountain_Valley",
        "Villa_Park",
        "Fillmore",
        "Goleta",
        "Arvin",
        "Glennville",
        "Hanford",
        "Kettleman_City",
        "Lake_Isabella",
        "Lamont",
        "Laton",
        "Lost_Hills",
        "Mc_Farland",
        "Pixley",
        "Springville",
        "Three_Rivers",
        "Tupman",
        "Weldon",
        "Woodlake",
        "Arroyo_Grande",
        "Atascadero",
        "Avila_Beach",
        "Cambria",
        "Cayucos",
        "Creston",
        "Grover_Beach",
        "Los_Olivos",
        "Paso_Robles",
        "San_Ardo",
        "San_Miguel",
        "San_Simeon",
        "Santa_Margarita",
        "Santa_Maria",
        "Santa_Ynez",
        "Shandon",
        "California_City",
        "Acton",
        "Bishop",
        "Bridgeport",
        "Darwin",
        "June_Lake",
        "Keeler",
        "Littlerock",
        "Llano",
        "Mammoth_Lakes",
        "Auberry",
        "Caruthers",
        "Chowchilla",
        "Coarsegold",
        "Del_Rey",
        "Dos_Palos",
        "Firebaugh",
        "Fish_Camp",
        "Lakeshore",
        "Los_Banos",
        "O_Neals",
        "Orange_Cove",
        "Raisin_City",
        "Raymond",
        "Reedley",
        "Sultana",
        "Wishon",
        "Gonzales",
        "Monterey",
        "Soledad",
        "Spreckels",
        "La_Honda",
        "Menlo_Park",
        "Montara",
        "Moss_Beach",
        "Pacifica",
        "San_Carlos",
        "San_Gregorio",
        "Stanford",
        "Alameda",
        "Alamo",
        "Benicia",
        "Bethel_Island",
        "Brentwood",
        "El_Cerrito",
        "Hercules",
        "Newark",
        "Suisun_City",
        "Yountville",
        "Belvedere_Tiburon",
        "Bodega",
        "Dillon_Beach",
        "Fairfax",
        "Lagunitas",
        "Penngrove",
        "Petaluma",
        "San_Geronimo",
        "San_Quentin",
        "Brookdale",
        "Castroville",
        "Mount_Hermon",
        "Paicines",
        "Scotts_Valley",
        "Saratoga",
        "Soquel",
        "Mount_Hamilton",
        "Burson",
        "Copperopolis",
        "Farmington",
        "Mokelumne_Hill",
        "San_Andreas",
        "Wilseyville",
        "Ceres",
        "Coulterville",
        "Cressey",
        "El_Nido",
        "El_Portal",
        "Escalon",
        "Hilmar",
        "Hornitos",
        "Keyes",
        "Le_Grand",
        "Manteca",
        "Midpines",
        "Ripon",
        "Sonora",
        "Tracy",
        "Twain_Harte",
        "Albion",
        "Boonville",
        "Cazadero",
        "Dos_Rios",
        "Duncans_Mills",
        "Forestville",
        "Fort_Bragg",
        "Geyserville",
        "Glenhaven",
        "Kelseyville",
        "Kenwood",
        "Little_River",
        "Lower_Lake",
        "Manchester",
        "Middletown",
        "Monte_Rio",
        "Occidental",
        "Potter_Valley",
        "Sebastopol",
        "Upper_Lake",
        "Willits",
        "Windsor",
        "Blocksburg",
        "Arcata",
        "Carlotta",
        "Fortuna",
        "Kneeland",
        "Mad_River",
        "Orick",
        "Orleans",
        "Phillipsville",
        "Scotia",
        "Redcrest",
        "Weott",
        "Willow_Creek",
        "Leggett",
        "Capay",
        "Courtland",
        "Esparto",
        "Fiddletown",
        "Foresthill",
        "Georgetown",
        "Ione",
        "Lincoln",
        "North_Highlands",
        "Placerville",
        "River_Pines",
        "Rocklin",
        "Shingle_Springs",
        "Somerset",
        "Volcano",
        "Alta",
        "Gold_Run",
        "Twin_Bridges",
        "El_Dorado_Hills",
        "Marysville",
        "Alleghany",
        "Berry_Creek",
        "Biggs",
        "Durham",
        "Glenn",
        "Goodyears_Bar",
        "Penn_Valley",
        "Greenville",
        "Meridian",
        "North_San_Juan",
        "Oregon_House",
        "Paradise",
        "Richvale",
        "Smartville",
        "Stirling_City",
        "Stonyford",
        "Washington",
        "Big_Bar",
        "Chester",
        "Forks_Of_Salmon",
        "French_Gulch",
        "Gazelle",
        "Gerber",
        "Grenada",
        "Hyampom",
        "Junction_City",
        "Lookout",
        "Mccloud",
        "Macdoel",
        "Manton",
        "Millville",
        "Montgomery_Creek",
        "Mount_Shasta",
        "Scott_Bar",
        "Tehama",
        "Weed",
        "Yreka",
        "Cedarville",
        "Chilcoot",
        "Clio",
        "Coleville",
        "Herlong",
        "Janesville",
        "Litchfield",
        "Loyalton",
        "Madeline",
        "Markleeville",
        "Milford",
        "Calpine",
        "Standish",
        "Tulelake",
        "Olympic_Valley",
    ],
    "Gender": ["Male", "Female"],
    "Senior_Citizen": ["No", "Yes"],
    "Partner": ["No", "Yes"],
    "Dependents": ["No", "Yes"],
    "Phone_Service": ["Yes", "No"],
    "Multiple_Lines": ["No", "Yes", "No_phone_service"],
    "Internet_Service": ["DSL", "Fiber optic", "No"],
    "Online_Security": ["Yes", "No", "No internet service"],
    "Online_Backup": ["Yes", "No", "No internet service"],
    "Device_Protection": ["No", "Yes", "No internet service"],
    "Tech_Support": ["No", "Yes", "No internet service"],
    "Streaming_TV": ["No", "Yes", "No internet service"],
    "Streaming_Movies": ["No", "Yes", "No internet service"],
    "Contract": ["Month-to-month", "One year", "Two year"],
    "Paperless_Billing": ["Yes", "No"],
    "Payment_Method": ["Electronic check", "Mailed check", "Bank transfer (automatic)", "Credit card (automatic)"],
}

# min, max, default value
floats = {"Monthly_Charges": [0.0, 1000.0, 100.0], "Total_Charges": [0.0, 50000.0, 1000.0]}

# min, max, default value
ints = {
    "Zip_Code": [90001, 96161, 90001],
    "Tenure_Months": [0, 100, 2],
}

labels = ["No", "Yes"]


def generate_input_lines():
    result = f"<table>"

    counter = 0
    for k in floats.keys():
        minn, maxx, vall = floats[k]
        if counter % 2 == 0:
            result += f"<tr>"
        result += f"<td>{k}"
        result += f'<input type="number" class="form-control" min="{minn}" max="{maxx}" step="1" name="{k}" id="{k}" value="{vall}" required (this.value)">'
        result += f"</td>"
        if counter % 2 == 1:
            result += f"</tr>"
        counter = counter + 1

    counter = 0
    for k in ints.keys():
        minn, maxx, vall = ints[k]
        if counter % 2 == 0:
            result += f"<tr>"
        result += f"<td>{k}"
        result += f'<input type="number" class="form-control" min="{minn}" max="{maxx}" step="1" name="{k}" id="{k}" value="{vall}" required (this.value)">'
        result += f"</td>"
        if counter % 2 == 1:
            result += f"</tr>"
        counter = counter + 1

    counter = 0
    for k in strings.keys():
        if counter % 2 == 0:
            result += f"<tr>"
        result += f"<td>{k}"
        result += f'<select class="form-control" name="{k}">'
        for value in strings[k]:
            result += f'<option value="{value}" selected>{value}</option>'
        result += f"</select>"
        result += f"</td>"
        if counter % 2 == 1:
            result += f"</tr>"
        counter = counter + 1

    result += f"</table>"

    return result


app.jinja_env.globals.update(generate_input_lines=generate_input_lines)


class churnForm:
    @app.route("/", methods=["GET", "POST"])
    def index():

        if request.method == "POST":
            ID = 999

            session["ID"] = ID
            data = {}

            for k, v in request.form.items():
                if k in floats:
                    data[k] = np.float64(v)
                elif k in ints:
                    data[k] = np.int64(v)
                else:
                    data[k] = v
                session[k] = v

            # Handle Lat and Long
            address = data["City"].replace("_", " ") + " " + str(data["Zip_Code"])
            url = "https://nominatim.openstreetmap.org/search/" + urllib.parse.quote(address) + "?format=json"
            response = requests.get(url).json()
            if not response:
                flash("City name and zip code do not match.Please input again!")
                return render_template("input.html")

            data["Latitude"] = np.float64(response[0]["lat"])
            data["Longitude"] = np.float64(response[0]["lon"])

            df_new_datapoint = pd.DataFrame(data, index=[0])
            new_datapoint_transformed = preprocessor.transform(df_new_datapoint)
            new_datapoint_encoded = pd.DataFrame(
                new_datapoint_transformed, columns=preprocessor.get_feature_names_out(), index=df_new_datapoint.index
            )

            result = model.predict_proba(new_datapoint_encoded)

            churn_risk = labels[np.argmax(result)]

            no_percent = result[0][0] * 100
            yes_percent = result[0][1] * 100
            flash("Percentage of this customer leaving is: %.0f%%" % yes_percent)
            result_dict = {"predictedLabel": str(churn_risk), "probability": [no_percent, yes_percent]}
            return render_template(
                "score.html",
                result=result_dict,
                churn_risk=churn_risk,
                yes_percent=yes_percent,
                no_percent=no_percent,
                labels=labels,
            )

        else:
            return render_template("input.html")


load_dotenv(os.path.join(os.path.dirname(__file__), ".env"))
port = os.environ.get("PORT", "5000")
host = os.environ.get("HOST", "0.0.0.0")
if __name__ == "__main__":
    app.run(host=host, port=int(port))
